### PR TITLE
fix more things 

### PR DESCRIPTION
**Pull request by sillyangel**
- New Readme
- Better Html

### CODE REVIEW

**Comment by Cerealistic** [comment]
Are you finished with this build? the html is empty.

**Comment by sillyangel** [comment]
im almost done

**Comment by sillyangel** [comment]
dont do it until Feb 3rd

**Comment by Cerealistic** [comment]
Okay!

**Comment by Cerealistic** [comment]
I noticed that you removed the chat script, please add this back as I am using a 3rd party service to host a chat.

**Comment by Cerealistic** [comment]
I noticed that the css is just google css, I do not feel like this fits the theme of the website. I was trying for a dark theme.

**Comment by rblxcollin** [comment]
Closing this because its outdated.

**Comment by sillyangel** [comment]
"outdated"

**Pull request closed without merging**
